### ISSUE TITLE
Fix template matching

### ISSUE THREAD

**Issue by emdupre** [rmarkello/peakdet#2]
Template matching currently doesn't detect real peaks.

**Comment by rmarkello** [comment]
#6 resolved issues with the template matching function in utils.py. This function now needs to be integrated into the PeakFinder class get_peaks() method.

**Comment by rmarkello** [comment]
Integrated into PeakFinder with https://github.com/rmarkello/peakdet/commit/457c0012a63a362101472f81df4f966249aea406.

Unfortunately, match_temp() takes an incredibly long time to run; ideally it could be cleaned up to run faster by taking advantage of broadcasting techniques in arrays, but I'm going to consider this issue resolved!
